create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  name text not null,
  balance numeric(12, 2) not null default 0,
  icon text not null default 'wallet',
  color text not null default '#60A5FA',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null check (type in ('income', 'expense')),
  amount numeric(12, 2) not null check (amount >= 0),
  category text not null,
  category_icon text not null default 'circle',
  account_id bigint not null references public.accounts(id) on delete cascade,
  date date not null,
  description text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_accounts_user_id on public.accounts (user_id);
create index if not exists idx_transactions_user_id on public.transactions (user_id);
create index if not exists idx_transactions_account_id on public.transactions (account_id);
create index if not exists idx_transactions_date on public.transactions (date desc);
